### ISSUE TITLE
Events consolidated into single table?

### ISSUE THREAD

**Issue by rrauenza** [Opus10/django-pghistory#7]
I'd like to replace my current auditing system, and have been studying your code tonight.   In order to change to this package I really need a way to query a single table with ordered events by time.

I've tried figuring out a way to change the Events base class to not be abstract... no success, and it would involve table inheritance.  Maybe an external table with content types that point to the actual tables?  

Do you have any suggestions as to how this could be done without modifying pghistory?

**Comment by rrauenza** [comment]
I think I've found a way to leverage pghistory and its Context model and middleware and make my own trigger on each audited table to insert into my own Events table, storing NEW and OLD as JSONB's....

**Comment by radusuciu** [comment]
Does this fit your use case?

https://django-pghistory.readthedocs.io/en/latest/extras.html#aggregating-events-with-aggregateevent

**Comment by wesleykendall** [comment]
@rrauenza yea the aggregate event model as pointed out above should allow you to consolidate events.

It sounds like what you are wanting to do might be a little less structured if you're talking about JSONB fields though. Do you want to be able to store historical changes that relate to the schema at that point in time? Currently pghistory doesn't support this use case, but I am considering it in a later iteration of this library.

I'm going to keep this open as an enhancement for now since I'm planning on finding a way to allow JSONBs to be tracked. Will report back when it's officially slated to be integrated

**Comment by wesleykendall** [comment]
Following up on some stale issues. Pghistory has primarily been centered around structured event models, and it's unlikely unstructured JSON will be supported as a first-class citizen now given how many code paths would have to be changed.

It's possible to write a history trigger with [django-pgtrigger](https://django-pgtrigger.readthedocs.io/en/4.12.0/) to log raw JSON in a single table. The more difficult part is attaching context tracked by pghistory. All generated pghistory triggers call `_pgh_attach_context()` to set the context in the global `Context` table and return the UUID to use in the foreign key. One could also grab the same SQL variables this function uses to store the context directly in the JSON table too.

I realize I'm circling back around to this pretty late. If there's still demand for a guide to do this, please open a [Discussion](https://github.com/Opus10/django-pghistory/discussions) and I'm happy to consider adding it in a later release
