### ISSUE TITLE
save some fields when it's changed

### ISSUE THREAD

**Issue by spinxi** [Opus10/django-pghistory#73]
well I need to save 2-3 fields when it changes
Now I have
`@pghistory.track(
    pghistory.BeforeUpdate(
        ("plate_number_changed"),
        condition=pgtrigger.Q(old__plate_number__df=pgtrigger.F("new__plate_number"))
    ),
    fields=["plate_number",'unit_number' "updated_by"],
    model_name="TrailerTracker",
) `
So, I need to add condition if change plate number, save it, if Change unit_number - save it. And save everytime updated_by without condition.
Is it accessible? or Should I need to create new tracks for every field...

**Comment by jacklinke** [comment]
I think you are overthinking this. Your use-case requires just storing a snapshot when any of your three fields changes - no condition is needed in most situations. All you need for this simple case is:

```python
@pghistory.track(
    pghistory.Snapshot(["my_app.my_model"]),
    fields=["plate_number", "unit_number", "updated_by"],
    model_name="TrailerTracker",
)
```

**Comment by wesleykendall** [comment]
Following up on some stale issues. Yes, you are correct that the current pghistory takes care of this with minimal configuration. The interface has been updated a bit since this original issue though.

To elaborate

```
@pghistory.track(
    pghistory.UpdateEvent(
        "plate_number_changed",
        row=pghistory.Old,
        condition=pghistory.AnyChange("plate_number")
    ),
    fields=["plate_number", "unit_number", "updated_by"],
   model_name="TrailerTracker"
)
class Trailer:
    ...
```

Above we:

1. Have a `TrailerTracker` model that tracks `["plate_number", "unit_number", "updated_by"]`
2. It is only created whenever there's a chance to `plate_number`.

to create this model whenever there are changes to `plate_number` or `unit_number`, update the condition:

```
@pghistory.track(
    pghistory.UpdateEvent(
        "plate_number_changed",
        row=pghistory.Old,
        condition=pghistory.AnyChange("plate_number", "unit_number")
    ),
    fields=["plate_number", "unit_number", "updated_by"],
    model_name="TrailerTracker"
)
class Trailer:
    ...
```

Note that you can also use `pghistory.AnyChange(exclude_auto=True)` to track any changes to `fields` except for the `auto_*` fields.

I believe some of the docs have been updated since, but I also tried to make the conditional tracking docs better in https://github.com/Opus10/django-pghistory/pull/145/files
