### ISSUE TITLE
Prevent database transaction when BeforeUpdate/Delete raises Exception

### ISSUE THREAD

**Issue by w4mike** [Opus10/django-pghistory#8]
Would there be a way to disable final database transaction if e.g. the BeforeUpdate/Delete raises an exception?

This would be a nice way to use the 'BeforeXXX' events as kind of a request of a user to ask for changes that need to be approved by another user.
If these Events had a 'needApprove' property, nice request/grant workflows could be created with this package. An approval could then apply the BeforeXXX event to the database.

Many thanks for your opinion and reply.

**Comment by wesleykendall** [comment]
@w4mike this is an interesting use case. The problem with disabling the final DB transaction like you mentioned means it would also not store the event since triggers run within the same transaction.

However, what might be possible is overriding the `Before...` trigger to `RETURN NULL;` at the end of the trigger. You'd have to do this by calling `super().get_func(model)` and then replace the return statement with the proper value. This would tell Postgres to ignore that operation from happening, but it would still store the event. You'd still have to figure out how to propagate this information to a user to let them know something needs approval. 

I don't think you need a `needApprove` property for the event either - You could just treat the event table as a list of events that need processing and then have another model that has a 1-1 reference to the event to mark it as processed. Not ideal, but it's one way of accomplishing it.

I'm planning on doing an overhaul on pghistory to make it more flexible for cases like this. Here are some things I'm planning to do that might help out your use case:

1. I'm planning to make the base model for events more flexible. Although you can currently [make a custom event model](https://django-pghistory.readthedocs.io/en/latest/tutorial.html#creating-a-custom-event-model), I don't think you'd be able to add in a custom boolean field with a default value. I'm planning to address this
2. I'm going to consider making the RETURN statement configurable so that you can `RETURN NULL` and block the operation while still writing the event.

I'm going to mark this as a question and leave it open until I have some of these features in place.
